name: "Merge a pull request automatically"
description: "GitHub Action to create pull request and merge automatically"
author: yyoshiki41
branding:
  icon: "git-merge"
  color: "green"

inputs:
  github-token:
    description: "Your GITHUB_TOKEN"
    required: true
  base:
    description: "The branch into which you want your code merged."
    required: true
  head:
    description: "The branch that contains commits for your pull request."
    required: true
  title:
    description: "Title"
    required: false
    default: "chore(auto-merge-action): merge automatically"
  body:
    description: "Title"
    required: false
    default: ""
  interval:
    description: "Refresh checks interval in seconds"
    required: false
    default: "15"

runs:
  using: "composite"
  steps:
    - name: Check pull requests
      shell: bash
      id: check_pr
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        num=$(gh api repos/:owner/:repo/pulls -q ".[] | select(.head.ref  == \"${{ inputs.head }}\") | select(.base.ref == \"${{ inputs.base }}\") | .number")
        echo "::set-output name=num::$num"
    - name: Create a pull request
      shell: bash
      if: ${{ steps.check_pr.outputs.num == '' }}
      id: check_diff
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        git fetch origin ${{ inputs.base }} ${{ inputs.head }}
        git diff --exit-code origin/${{ inputs.base }}...origin/${{ inputs.head }} > /dev/null
        if [ $? -ne 0 ]; then
          gh pr create -H ${{ inputs.head }} -B ${{ inputs.base }} -t "${{ inputs.title }}" -b "${{ inputs.body }}"
        fi
    # NOTE: merge will fail if the necessary requirements are not completed
    - name: Merge a pull request if exist
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        num=$(gh api repos/:owner/:repo/pulls -q ".[] | select(.head.ref  == \"${{ inputs.head }}\") | select(.base.ref == \"${{ inputs.base }}\") | .number")
        if [ -n "$num" ]; then
          gh pr merge ${num} --merge
        fi
