name: "Merge a pull request automatically"
description: "GitHub Action to create pull request and merge automatically"
author: yyoshiki41
branding:
  icon: "git-merge"
  color: "green"

inputs:
  github-token:
    description: "Your GITHUB_TOKEN"
    required: true
  base:
    description: "The branch into which you want your code merged."
    required: true
  head:
    description: "The branch that contains commits for your pull request."
    required: true
  title:
    description: "Title"
    required: false
    default: "chore(auto-merge-action): merge automatically"
  body:
    description: "Body"
    required: false
    default: ""

outputs:
  num:
    description: "Pull Request Number"
    value: ${{ steps.merge-pr.outputs.num }}

runs:
  using: "composite"
  steps:
    - name: Check pull requests
      shell: bash
      id: check-pr
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        num=$(gh api repos/:owner/:repo/pulls -q ".[] | select(.head.ref  == \"${{ inputs.head }}\") | select(.base.ref == \"${{ inputs.base }}\") | .number")
        echo "::set-output name=num::$num"
    - name: Create a pull request
      shell: bash
      if: ${{ steps.check-pr.outputs.num == '' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        git fetch origin ${{ inputs.base }} ${{ inputs.head }}
        code=(git diff --exit-code --quiet origin/${{ inputs.base }}...origin/${{ inputs.head }} || echo $?)
        if [ $code -ne 0 ]; then
          gh pr create -H ${{ inputs.head }} -B ${{ inputs.base }} -t "${{ inputs.title }}" -b "${{ inputs.body }}"
        fi
    - name: Merge a pull request if exist
      shell: bash
      id: merge-pr
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        num=$(gh api repos/:owner/:repo/pulls -q ".[] | select(.head.ref  == \"${{ inputs.head }}\") | select(.base.ref == \"${{ inputs.base }}\") | .number")
        if [ -n "$num" ]; then
          gh pr merge ${num} --merge
          echo "::set-output name=number::$num"
        fi
